import requests
import sqlite3
import random
import string
import os
import sys
import time
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv(os.path.join(os.path.dirname(__file__), '.env'))

# Add the project root to the python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import (
    adder, 
    check_password, 
    update_pss, 
    delete_user, 
    store_otp, 
    verify_otp, 
    get_user_by_identifier,
    get_user_profile,
    search_courses,
    get_all_courses
)
from flask import Flask, request, redirect, url_for, session, render_template, render_template_string, send_from_directory, jsonify

# Gemini API Configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Using the latest available model as of March 2026
GEMINI_API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent?key={GEMINI_API_KEY}"

# Path to the static export generated by Next.js
frontend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'ROOTS', 'out'))

app = Flask(__name__, 
            static_folder=frontend_dir, 
            static_url_path='')

# Keep this secret in a real application!
app.secret_key = 'super_secret_development_key'

# Dictionary mapping course IDs to external video URLs
COURSE_LINKS = {}

# --- SPA Routing Helpers ---
@app.route('/')
def serve_index():
    if os.path.exists(os.path.join(app.static_folder, 'index.html')):
        return send_from_directory(app.static_folder, 'index.html')
    return "UI is building... please wait and refresh in a minute."

@app.route('/root')
@app.route('/dashboard')
@app.route('/courses')
@app.route('/streak')
@app.route('/tree')
def serve_pages():
    path = request.path.strip('/')
    html_file = f"{path}.html"
    if os.path.exists(os.path.join(app.static_folder, html_file)):
        return send_from_directory(app.static_folder, html_file)
    # Fallback to index if subpage not found (for SPA behavior)
    return send_from_directory(app.static_folder, 'index.html')

# --- API Endpoints ---
@app.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    identifier = data.get('identifier')
    password = data.get('password')
    
    result = check_password(identifier, password)
    if result != "correct pass":
        name = get_user_by_identifier(identifier)
        if name:
            result = check_password(name, password)
            if result == "correct pass":
                session['user_name'] = name
                return jsonify({"status": "success", "message": "Login successful"})
        return jsonify({"status": "error", "message": result})
    
    session['user_name'] = identifier
    return jsonify({"status": "success", "message": "Login successful"})

@app.route('/signup', methods=['POST'])
def signup():
    data = request.get_json()
    name = data.get('name')
    email = data.get('email')
    password = data.get('password')
    number = data.get('number', '')
    
    result = adder(name, email, password, number)
    if result == "Inserted successfully!":
        session['user_name'] = name
        return jsonify({"status": "success", "message": "Signup successful"})
    else:
        return jsonify({"status": "error", "message": result})

@app.route('/otp-request', methods=['POST'])
def otp_request_api():
    data = request.get_json()
    identifier = data.get('identifier')
    user_name = get_user_by_identifier(identifier)
    if user_name:
        otp = ''.join(random.choices(string.digits, k=6))
        if store_otp(identifier, otp):
            print(f"DEBUG: Sending OTP {otp} to {identifier}")
            session['otp_identifier'] = identifier
            return jsonify({"status": "success", "message": "OTP sent"})
        return jsonify({"status": "error", "message": "Error storing OTP"})
    return jsonify({"status": "error", "message": "User not found"})

@app.route('/otp-verify', methods=['POST'])
def otp_verify_api():
    data = request.get_json()
    otp = data.get('otp')
    identifier = session.get('otp_identifier')
    if not identifier:
        return jsonify({"status": "error", "message": "No OTP session active"})
    
    if verify_otp(identifier, otp):
        user_name = get_user_by_identifier(identifier)
        session['user_name'] = user_name
        session.pop('otp_identifier', None)
        return jsonify({"status": "success", "message": "OTP verified"})
    return jsonify({"status": "error", "message": "Invalid OTP"})

@app.route('/logout')
def logout():
    session.pop('user_name', None)
    return jsonify({"status": "success", "message": "Logged out"})

@app.route('/api/chat', methods=['POST'])
def chat():
    if not GEMINI_API_KEY:
        return jsonify({"status": "error", "message": "API key not configured"}), 500
    
    data = request.get_json()
    user_message = data.get('message')
    history = data.get('history', []) 
    
    # Gemini API requires the conversation to start with a 'user' turn.
    # If the history starts with a 'model' turn, we skip it.
    while history and history[0].get('role') == 'model':
        history.pop(0)

    # System context for the AI with safety guardrails
    system_prompt = (
        "You are ROOTS AI, an advanced, futuristic learning guide within 'The Living Roots' platform. "
        "Your goal is to guide users through the roots of technology (Web Dev, Data Science, Cybersecurity, etc.). "
        "STRICT GUARDRAILS:\n"
        "1. Focus ONLY on technology, programming, career guidance, and the ROOTS platform. "
        "2. Refuse to answer questions about illegal activities, hacking for harm, or creating malware. "
        "3. Do not provide medical, legal, or financial advice. "
        "4. If a user asks something dangerous, offensive, or completely unrelated to learning, "
        "politely decline and redirect them to 'expanding their roots' in technology.\n"
        "Keep responses concise, helpful, and maintain a slightly cyberpunk/futuristic tone. "
        "Refer to 'growing roots' and 'expanding branches' when appropriate."
    )
    
    payload = {
        "contents": history + [{"role": "user", "parts": [{"text": user_message}]}],
        "system_instruction": {
            "parts": [{"text": system_prompt}]
        },
        "generationConfig": {
            "temperature": 0.8,
            "topP": 0.9,
            "topK": 40,
            "maxOutputTokens": 1024,
        }
    }
    
    # Retry mechanism for 429 errors
    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = requests.post(GEMINI_API_URL, json=payload)
            if response.status_code == 429:
                wait_time = (attempt + 1) * 2 # Exponential backoff: 2s, 4s, 6s
                print(f"Rate limited (429). Retrying in {wait_time}s... (Attempt {attempt + 1}/{max_retries})")
                time.sleep(wait_time)
                continue
            
            if response.status_code != 200:
                print(f"Gemini API Error {response.status_code}: {response.text}")
                return jsonify({"status": "error", "message": f"Gemini API Error: {response.text}"}), response.status_code
                
            resp_data = response.json()
            
            # Extract assistant response
            if 'candidates' in resp_data and resp_data['candidates']:
                candidate = resp_data['candidates'][0]
                if 'content' in candidate and 'parts' in candidate['content']:
                    assistant_text = candidate['content']['parts'][0]['text']
                    return jsonify({"status": "success", "text": assistant_text})
                elif 'finishReason' in candidate:
                    return jsonify({"status": "error", "message": f"AI finished with reason: {candidate['finishReason']}"}), 500
            
            return jsonify({"status": "error", "message": "Unexpected response format from Gemini"}), 500
        except Exception as e:
            if attempt == max_retries - 1:
                print(f"Chat API error after {max_retries} attempts: {e}")
                return jsonify({"status": "error", "message": str(e)}), 500
            time.sleep(1) # Small wait for other errors

    return jsonify({"status": "error", "message": "Max retries exceeded"}), 500

@app.route('/api/session')
def get_session():
    if 'user_name' in session:
        profile = get_user_profile(session['user_name'])
        return jsonify({
            "status": "success", 
            "user": {
                "name": profile['name'] if profile else session['user_name'],
                "email": profile['email'] if profile else "No email found",
                "level": 1, 
                "xp": 0,
                "maxXP": 1000,
                "streak": 0,
                "longestStreak": 0,
                "totalXPEarned": 0,
                "sessionsThisMonth": 0
            }
        })
    return jsonify({"status": "error", "message": "Not logged in"}), 401

@app.route('/api/courses')
def get_courses():
    topic = request.args.get('topic')
    if topic:
        courses = search_courses(topic)
    else:
        courses = get_all_courses()
    return jsonify({"status": "success", "courses": courses})

@app.route('/play/<course_id>')
def play_course(course_id):
    if course_id in COURSE_LINKS:
        return redirect(COURSE_LINKS[course_id])
    return "Course not found", 404

# Serve static assets (_next, etc.)
@app.route('/<path:filename>')
def serve_static(filename):
    return send_from_directory(app.static_folder, filename)

if __name__ == '__main__':
    app.run(debug=True, port=5000)
